### ISSUE TITLE
[REG] OCF resource properties items are missing when the demo is built on cordova-plugin-ocf v0.6.4

### ISSUE THREAD

**Issue by qiuzhong** [siovene/cordova-plugin-oic-demo#15]
# Steps:
1. Build the demo app, launch it.
2. After an OCF resource is found, go to the detailed page of the resource.

When the app is built on the [cordova-plugin-ocf](https://github.com/01org/cordova-plugin-ocf) <strong>v0.6.3</strong>, the properties items can be listed, see the screenshot:
![screenshot_20170120-003842](https://cloud.githubusercontent.com/assets/11829497/22094188/83acb896-de46-11e6-8a9f-23410ce1b9ec.png)

However, when it's built on the plugin <strong>v0.6.4</strong>, the properties items are gone:
![screenshot_20170120-003555](https://cloud.githubusercontent.com/assets/11829497/22094197/97298a98-de46-11e6-9696-a8b03287db6a.png)

# Test envrionments

* Cordova-plugin-ocf-demo:  [f45eab2](https://github.com/siovene/cordova-plugin-ocf-demo/commit/f45eab2a19a898ed6006fc7c221c2e8fe770394d)
* Nexus 6P: Android 6.0

**Comment by siovene** [comment]
Fixed by releasing cordova-plugin-ocf 0.6.5. Please rebuild against that one to verify. Thanks!

**Comment by qiuzhong** [comment]
Verified. Tested on the this demo app built on the cordova-plugin-ocf <strong>v0.6.5</strong> and it's been fixed.
