### ISSUE TITLE
Error: Cannot find module 'bplist-parser'

### ISSUE THREAD

**Issue by zqzhang** [siovene/cordova-plugin-oic-demo#3]
`grunt platform:add:android` shows these error messages:

``` text
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'bplist-parser'
Warning: Task "platform:add:android" not found. Use --force to continue.

Aborted due to warnings.
```

I tried 

``` sh
sudo npm cache clean
sudo npm update -g
```

... but no luck.

``` sh
sudo npm install -g bplist-parser
```

... is also helpless.

Any tips?

**Comment by siovene** [comment]
Can I have a full log please? Thanks!

**Comment by zqzhang** [comment]
Actually that's the full log.

``` text
~/work/cordova-plugin-oic-demo$ grunt platform:add:android
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'bplist-parser'
Warning: Task "platform:add:android" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by siovene** [comment]
Ubuntu 14.04 ships with a version of nodejs that is too old. The problem should be gone if you install nodejs v5, like this:

```
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs
```

I will update the README with this mention.

**Comment by siovene** [comment]
PS: you might want to delete the `node_modules` directory and do `npm install` again, to be on the safe side.

**Comment by siovene** [comment]
PPS: you might want to also issue `sudo npm -g update` to update the global modules.

**Comment by siovene** [comment]
And final comment (I hope...) I suppose something is broken somewhere for older Ubuntu (14.04 is now 2 years old and not the current LTS).

Even after all the steps above I still needed to do `sudo npm install -g bplist-parser` to make things worker, while this is not necessary in Ubuntu 15.04.

**Comment by zqzhang** [comment]
> curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

Nothing happened when execute this command; either this command:

``` sh
wget -qO- https://deb.nodesource.com/setup_5.x | sudo -E  bash -
```

Will further check the issue next week.

**Comment by siovene** [comment]
Remember that you're behind a proxy. You probably need to export `http_proxy` and `https_proxy`.

**Comment by zqzhang** [comment]
Still no lucky with `http_proxy` and `https_proxy` exported.

`curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -` returned this error message:

``` text
W: Failed to fetch https://deb.nodesource.com/node_5.x/dists/trusty/main/source/Sources  gnutls_handshake() failed: A TLS packet with unexpected length was received.

W: Failed to fetch https://deb.nodesource.com/node_5.x/dists/trusty/main/binary-amd64/Packages  gnutls_handshake() failed: A TLS packet with unexpected length was received.

W: Failed to fetch https://deb.nodesource.com/node_5.x/dists/trusty/main/binary-i386/Packages  gnutls_handshake() failed: A TLS packet with unexpected length was received.

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Still got this error message after compile and install `git` following

http://askubuntu.com/questions/186847/error-gnutls-handshake-failed-when-connecting-to-https-servers

**Comment by zqzhang** [comment]
Workaround this issue by manually removing existing node.js installed, and downloading, building and installing node.js v5.6.0

Now done the `grunt platform:add:android` without errors, only 2 warnings:

``` text
>> (node) sys is deprecated. Use util instead.
>> (node) util.puts is deprecated. Use console.log instead.
```
