### ISSUE TITLE
Temperature value cannot convert automatically between Celsius and Fahrenheit units

### ISSUE THREAD

**Issue by qiuzhong** [siovene/cordova-plugin-oic-demo#7]
After the demo app found a temperature resource, the value couldn't convert automatically in different temperature units.

Steps:
1. Setup a temperature OIC resource, and make sure the demo app can find this resource.
2. Launch the demo app and enter the "Resources" page, click the temperature resource item, and click the pencil button in the **units** line of the **Properties** section, try to update the unit from "C" to "F",  and click "Save" button the temperature value still remains the same value.

**Comment by siovene** [comment]
Hi, I think something went wrong when you posted this issue? The title seems incomplete and there's no description.

**Comment by qiuzhong** [comment]
Sorry, I press the Enter key accidentally when editing the title.

**Comment by siovene** [comment]
@nagineni, does the temperature server support modifying the **unit** field? If not, is there a way to know that that field is read-only?

**Comment by nagineni** [comment]
> does the temperature server support modifying the unit field? 

It's a read-only property, but the client can specify the units for the requested temperature by using query parameter.

e.g /a/temperature?di=<devid>&units=K

> If not, is there a way to know that that field is read-only?

I don't think there is any way to know other than the "description" mentioned in the docs.
https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/doc/oic.r.temperature.json#L15

**Comment by wanghongjuan** [comment]
Hi, @nagineni 

> It's a read-only property, but the client can specify the units for the requested temperature by using query parameter. 
> e.g /a/temperature?di=&units=K

I tried to using `/a/temperature?di=&units=K` to specify the units, but it doesn't work, get message as below:
`{"properties":{"id":"temperature","temperature":26.8,"units":"C","range":"-40,125"}}`

**Comment by nagineni** [comment]
Which version of iotivity-node you are using at server side?

**Comment by nagineni** [comment]
You need to use the latest version of iotivity-node which contains a fix for parsing query string.

**Comment by wanghongjuan** [comment]
The latest version of iotivity-node in Ostro image is 1.1.0-4, so I will re-test it after the version update to you mentioned.
